### ISSUE TITLE
Add exercise on flex axis and make axis descriptions consistent for all exercises.

### ISSUE THREAD

**Issue by NateWr** [NateWr/html-css-git-exercises#9]
The phrase "non-main axis" is used in https://github.com/NateWr/html-css-git-exercises/blob/master/week-2/14-align-self/readme.md. Once the axis exercise is added, make sure that language is consistent with the original usage. :+1:

**Comment by rarmatei** [comment]
add this as well to the readme: 
![image](https://user-images.githubusercontent.com/5975076/50742212-bc009c00-11ff-11e9-8578-7f2b23148145.png)

**Comment by NateWr** [comment]
Added as part of https://github.com/NateWr/html-css-git-exercises/pull/13
